services:
  caddy:
      image: caddy:2.11.4
      restart: unless-stopped
      container_name: caddy
      environment:
        - TZ=America/Bogota
      ports:
        - 80:80
        - 443:443
        - 443:443/udp
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./site:/srv
        - caddy_data:/data
        - caddy_config:/config
      networks:
        - reverse_proxy
volumes:
  caddy_config:
  caddy_data:
    
networks:
  reverse_proxy:
     external: true
