services:
  caddy:
      image: caddy:latest
      restart: unless-stopped
      container_name: caddy
      environment:
        - TZ=America/Bogota
      cap_add:
      - NET_ADMIN  
      ports:
        - 82:80
        - 446:443
         - 443:443/udp
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./site:/srv
        - caddy_data:/data
        - caddy_config:/config
      networks:
        - reverse_proxy
volumes:
  caddy_config:
  caddy_data:
    
networks:
  reverse_proxy:
     external: true
